### ISSUE TITLE
validation reports not written if they aren't all written

### ISSUE THREAD

**Issue by chris-s-friedman** [kids-first/kf-lib-data-ingest#538] opened 2020-12-03 20:52 UTC
attempting to run `kidsfirst test` fails. 

```
2020-12-03 15:21:21,085 - MarkdownReportBuilder - Thread: MainThread - INFO - Begin building validation report ...
2020-12-03 15:21:21,558 - MarkdownReportBuilder - Thread: MainThread - INFO - Wrote validation report file(s):
['/Users/friedmanc1/Documents/kf-ingest-packages/kf_ingest_packages/packages/SD_Z6MWD3H0/clinical_data_review-ds_chd/output/ExtractStage/validation_results/validation_results.md']
2020-12-03 15:21:21,558 - HtmlReportBuilder - Thread: MainThread - INFO - Begin building validation report ...
2020-12-03 15:21:22,061 - Validator - Thread: MainThread - ERROR - SubElement() argument 1 must be xml.etree.ElementTree.Element, not Element
Traceback (most recent call last):
...blah blah blah...
```

Error reason not important. ExtractStage/validation_results/validation_results.md not found despite the claim that it was written.

**Comment by fiendish** [comment] 2020-12-08 14:59
Mine just broke in the same place and I found the md report file. I'm going to close this for now and focus on fixing the Element issue.

**Closed by fiendish** 2020-12-08 14:59 UTC

**Comment by fiendish** [comment] 2020-12-08 17:27
(Element error is caused by defusedxml doing something bad. Temporary solution is to pip uninstall defusedxml.)
